/**
 * Landscaping & gardening catalog - browsable reference data, not AI
 * output. Compiled from a dedicated research pass (multiple independent
 * nursery/horticulture sources, cross-checked for agreement) - see the
 * research reference document from that pass. `keywords` exists for the
 * same reason it does in the Standard Heights data: search should match
 * how people actually talk ("toilet" finds WC; here, "bedroom plant"
 * should find the same low-light entries "low light" does).
 *
 * Real product photography for these entries is a separate, later step -
 * this file is text/data only. See the research note on image licensing.
 */

export type PlantEntry = {
  category: "interior" | "exterior-tree" | "exterior-shrub" | "exterior-succulent" | "exterior-climber" | "lawn-grass";
  name: string;
  benefit: string;
  care: string;
  keywords: string;
  /** Populated by scripts/fetch-catalog-images.mjs against the Pexels API - undefined until that's run. */
  imageUrl?: string;
  photographerName?: string;
  photographerUrl?: string;
};

export const PLANT_ENTRIES: PlantEntry[] = [
  // ===== INTERIOR PLANTS =====
  { category: "interior", name: "Snake Plant (Sansevieria)", benefit: "Releases oxygen at night; among the most tolerant of neglect.", care: "Low light; water rarely.", keywords: "mother in law tongue bedroom low light air purifying" , imageUrl: "https://images.pexels.com/photos/12174069/pexels-photo-12174069.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Alexey Demidov", photographerUrl: "https://www.pexels.com/@alexeydemidov" },
  { category: "interior", name: "Money Plant (Pothos)", benefit: "Most popular indoor plant in India; removes formaldehyde and benzene; Vastu significance for luck and prosperity.", care: "Low-medium light; water when soil is dry.", keywords: "pothos vastu lucky trailing hanging" , imageUrl: "https://images.pexels.com/photos/1374879/pexels-photo-1374879.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Khanh Nguyen", photographerUrl: "https://www.pexels.com/@khanh-nguyen-210478" },
  { category: "interior", name: "Areca Palm", benefit: "Natural humidifier; filters xylene and toluene.", care: "Bright indirect light; keep soil moist.", keywords: "palm tropical living room" , imageUrl: "https://images.pexels.com/photos/12349129/pexels-photo-12349129.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Alexey Demidov", photographerUrl: "https://www.pexels.com/@alexeydemidov" },
  { category: "interior", name: "Peace Lily", benefit: "White flowers; absorbs mold spores - good for humid bathrooms.", care: "Low-medium light; water when dry.", keywords: "flowering bathroom humidity" , imageUrl: "https://images.pexels.com/photos/38933367/pexels-photo-38933367.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Ilo Frey", photographerUrl: "https://www.pexels.com/@couleur" },
  { category: "interior", name: "Spider Plant", benefit: "Removes up to 90% of formaldehyde within 24 hours (NASA); also filters carbon monoxide.", care: "Tolerates most conditions; beginner-friendly.", keywords: "hanging balcony air purifying" , imageUrl: "https://images.pexels.com/photos/32667143/pexels-photo-32667143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Magda Ehlers", photographerUrl: "https://www.pexels.com/@magda-ehlers-pexels" },
  { category: "interior", name: "ZZ Plant", benefit: "Extremely low maintenance; near-indestructible.", care: "Low light; water every 2-3 weeks.", keywords: "low light forgetful office" , imageUrl: "https://images.pexels.com/photos/9507221/pexels-photo-9507221.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "ROCKETMANN TEAM", photographerUrl: "https://www.pexels.com/@rocketmann-prod" },
  { category: "interior", name: "Aloe Vera", benefit: "Medicinal gel; easy to propagate.", care: "Bright light; infrequent watering.", keywords: "medicinal succulent" , imageUrl: "https://images.pexels.com/photos/12448627/pexels-photo-12448627.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Alexey Demidov", photographerUrl: "https://www.pexels.com/@alexeydemidov" },
  { category: "interior", name: "Boston Fern", benefit: "Natural humidifier.", care: "Indirect light; needs regular misting.", keywords: "fern humidity hanging" , imageUrl: "https://images.pexels.com/photos/3854761/pexels-photo-3854761.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Joshua Mcknight", photographerUrl: "https://www.pexels.com/@joshuamckn" },
  { category: "interior", name: "Lucky Bamboo", benefit: "Symbol of fortune; grows in water alone, no soil needed.", care: "Low light; water-based.", keywords: "feng shui desk fortune" , imageUrl: "https://images.pexels.com/photos/13677856/pexels-photo-13677856.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Markus Winkler", photographerUrl: "https://www.pexels.com/@markus-winkler-1430818" },
  { category: "interior", name: "Tulsi (Holy Basil)", benefit: "Culturally significant; common in Indian homes for religious and air-quality reasons.", care: "Bright light, ideally a sunny window or courtyard.", keywords: "holy basil religious courtyard" , imageUrl: "https://images.pexels.com/photos/35971056/pexels-photo-35971056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Pavan Prasad", photographerUrl: "https://www.pexels.com/@pavan-prasad-2156671405" },
  { category: "interior", name: "Rubber Plant", benefit: "Tolerates air-conditioned rooms with occasional misting.", care: "Bright indirect light.", keywords: "ficus elastica statement" , imageUrl: "https://images.pexels.com/photos/1903964/pexels-photo-1903964.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Scott Webb", photographerUrl: "https://www.pexels.com/@scottwebb" },
  { category: "interior", name: "Chinese Evergreen (Aglaonema)", benefit: "Low-light tolerant; decorative variegated varieties available.", care: "Low-medium light.", keywords: "aglaonema variegated colourful" , imageUrl: "https://images.pexels.com/photos/3119964/pexels-photo-3119964.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "K", photographerUrl: "https://www.pexels.com/@kelly" },
  { category: "interior", name: "Cast Iron Plant", benefit: "Extremely hardy, tolerates near-total neglect.", care: "Low light.", keywords: "hardy indestructible shade" , imageUrl: "https://images.pexels.com/photos/38843959/pexels-photo-38843959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Karen F", photographerUrl: "https://www.pexels.com/@karen-f-1376469" },
  { category: "interior", name: "Fiddle Leaf Fig", benefit: "Popular large decorative statement plant.", care: "Bright indirect light.", keywords: "statement large leaf decor" , imageUrl: "https://images.pexels.com/photos/5635485/pexels-photo-5635485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Gustavo Fring", photographerUrl: "https://www.pexels.com/@gustavo-fring" },
  { category: "interior", name: "Philodendron", benefit: "Trailing or climbing habit; several colour variants (including pink).", care: "Low-medium light.", keywords: "trailing climbing pink variant" , imageUrl: "https://images.pexels.com/photos/5607881/pexels-photo-5607881.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "cottonbro studio", photographerUrl: "https://www.pexels.com/@cottonbro" },

  // ===== EXTERIOR TREES =====
  { category: "exterior-tree", name: "Ficus (Banyan / Fig varieties)", benefit: "Large shade tree; highly tolerant of varied conditions.", care: "Well-draining soil, bright indirect to full light.", keywords: "banyan fig shade large tree" , imageUrl: "https://images.pexels.com/photos/12567701/pexels-photo-12567701.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Zaid Ahmed", photographerUrl: "https://www.pexels.com/@zaid-ahmed-80609047" },
  { category: "exterior-tree", name: "Plumeria (Frangipani)", benefit: "Fragrant flowers; sculptural branch structure even without bloom.", care: "Warm, bright conditions.", keywords: "frangipani fragrant entrance courtyard" , imageUrl: "https://images.pexels.com/photos/34190490/pexels-photo-34190490.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "hartono subagio", photographerUrl: "https://www.pexels.com/@hartonosbg" },
  { category: "exterior-tree", name: "Cassia fistula", benefit: "Native flowering tree, considered one of India's most beautiful.", care: "Open outdoor space, full sun.", keywords: "golden shower native flowering" , imageUrl: "https://images.pexels.com/photos/32471813/pexels-photo-32471813.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Hồng Quang Official", photographerUrl: "https://www.pexels.com/@h-ng-quang-official-647624701" },
  { category: "exterior-tree", name: "Butea monosperma", benefit: "Striking native tree for large open spaces.", care: "Full sun, established outdoor planting.", keywords: "flame of forest native large" , imageUrl: "https://images.pexels.com/photos/36783663/pexels-photo-36783663.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Rohan", photographerUrl: "https://www.pexels.com/@rohan-2158121582" },
  { category: "exterior-tree", name: "Neem (Azadirachta indica)", benefit: "Drought-tolerant; environmentally beneficial, natural pest deterrent.", care: "Minimal water once established.", keywords: "neem drought tolerant native" , imageUrl: "https://images.pexels.com/photos/17715129/pexels-photo-17715129.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "RonaK PitambeR ChoudharY", photographerUrl: "https://www.pexels.com/@ronak-pitamber-choudhary-251114364" },
  { category: "exterior-tree", name: "Peepal (Ficus religiosa)", benefit: "Culturally significant; supports biodiversity.", care: "Large space needed, full sun.", keywords: "peepal religious sacred large" , imageUrl: "https://images.pexels.com/photos/37108157/pexels-photo-37108157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Saravanan Narayanan", photographerUrl: "https://www.pexels.com/@snsn" },
  { category: "exterior-tree", name: "Ashoka Tree (Polyalthia longifolia)", benefit: "Popular for boundary and entrance plantings; tall, narrow form.", care: "Full sun, regular watering while establishing.", keywords: "boundary entrance tall narrow privacy" , imageUrl: "https://images.pexels.com/photos/1058072/pexels-photo-1058072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Satish Vasava", photographerUrl: "https://www.pexels.com/@satishvasava" },
  { category: "exterior-tree", name: "Crepe Myrtle (Lagerstroemia)", benefit: "Easy-care flowering patio tree.", care: "Full sun.", keywords: "flowering patio easy care" , imageUrl: "https://images.pexels.com/photos/10962066/pexels-photo-10962066.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Dion Wijaya", photographerUrl: "https://www.pexels.com/@dionwijaya" },

  // ===== EXTERIOR FLOWERING SHRUBS =====
  { category: "exterior-shrub", name: "Bougainvillea", benefit: "Vigorous, thorny; near-year-round colour in pink, purple, orange, white, red.", care: "Full sun; drought-tolerant once established.", keywords: "colourful thorny climber hedge" , imageUrl: "https://images.pexels.com/photos/11069352/pexels-photo-11069352.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Markus Winkler", photographerUrl: "https://www.pexels.com/@markus-winkler-1430818" },
  { category: "exterior-shrub", name: "Hibiscus", benefit: "Large, eye-catching blooms; more profuse flowering in full sun.", care: "Full sun, regular watering.", keywords: "large flower classic garden" , imageUrl: "https://images.pexels.com/photos/15480253/pexels-photo-15480253.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "rajan vijayakumar", photographerUrl: "https://www.pexels.com/@vijayakumar" },
  { category: "exterior-shrub", name: "Ixora", benefit: "Clusters of bright flowers almost year-round.", care: "Full sun to partial shade.", keywords: "border hedge continuous colour" , imageUrl: "https://images.pexels.com/photos/30122834/pexels-photo-30122834.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Fandy Much", photographerUrl: "https://www.pexels.com/@fandymuch" },
  { category: "exterior-shrub", name: "Jasmine (Mogra)", benefit: "Fragrant white flowers.", care: "Needs plenty of sun to keep flowering.", keywords: "fragrant white flower mogra" , imageUrl: "https://images.pexels.com/photos/14771827/pexels-photo-14771827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Quang Nguyen Vinh", photographerUrl: "https://www.pexels.com/@quang-nguyen-vinh-222549" },
  { category: "exterior-shrub", name: "Oleander (Nerium)", benefit: "Long-lasting blooms; hardy shrub.", care: "Full sun.", keywords: "hardy long blooming" , imageUrl: "https://images.pexels.com/photos/35425420/pexels-photo-35425420.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Alexander Popadin", photographerUrl: "https://www.pexels.com/@irrabagon" },
  { category: "exterior-shrub", name: "Tecoma (Yellow Bells)", benefit: "Fast-growing, trumpet-shaped yellow flowers.", care: "Full sun; reaches 6-10 feet.", keywords: "yellow fast growing tall" , imageUrl: "https://images.pexels.com/photos/38216871/pexels-photo-38216871.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Saravanan Narayanan", photographerUrl: "https://www.pexels.com/@snsn" },
  { category: "exterior-shrub", name: "Plumbago", benefit: "Soft blue flower clusters, unusual colour for a shrub.", care: "Full sun to partial shade.", keywords: "blue flower unusual colour" , imageUrl: "https://images.pexels.com/photos/6705154/pexels-photo-6705154.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Nilanka Sampath", photographerUrl: "https://www.pexels.com/@nilanka-sampath-2852976" },
  { category: "exterior-shrub", name: "Duranta (Golden Dewdrop)", benefit: "Evergreen; popular for hedges and borders.", care: "Full sun.", keywords: "hedge border evergreen" , imageUrl: "https://images.pexels.com/photos/35618159/pexels-photo-35618159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Domenico Adornato", photographerUrl: "https://www.pexels.com/@dome2906" },
  { category: "exterior-shrub", name: "Gardenia", benefit: "Fragrant white flowers.", care: "Partial shade, consistent moisture.", keywords: "fragrant white classic" , imageUrl: "https://images.pexels.com/photos/36506737/pexels-photo-36506737.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Jeffry Surianto", photographerUrl: "https://www.pexels.com/@andromeda99" },
  { category: "exterior-shrub", name: "Croton", benefit: "Colourful foliage year-round, not dependent on flowering.", care: "Bright light for best colour.", keywords: "colourful foliage year round" , imageUrl: "https://images.pexels.com/photos/11457413/pexels-photo-11457413.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Erik Mclean", photographerUrl: "https://www.pexels.com/@introspectivedsgn" },
  { category: "exterior-shrub", name: "Lantana", benefit: "Extremely hardy, minimal maintenance, attracts butterflies.", care: "Full sun, drought-tolerant.", keywords: "hardy butterfly low maintenance" , imageUrl: "https://images.pexels.com/photos/25014421/pexels-photo-25014421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Duy Le Duc", photographerUrl: "https://www.pexels.com/@duy-le-duc-1257907900" },

  // ===== SUCCULENTS / DROUGHT-TOLERANT =====
  { category: "exterior-succulent", name: "Agave", benefit: "Architectural, bold statement plant.", care: "Full sun, minimal water.", keywords: "architectural bold statement drought" , imageUrl: "https://images.pexels.com/photos/12577047/pexels-photo-12577047.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Jose de los Santos Calderón", photographerUrl: "https://www.pexels.com/@joscalderonj" },
  { category: "exterior-succulent", name: "Crown of Thorns (Euphorbia milii)", benefit: "Flowering succulent, tolerates heat and low water.", care: "Full sun.", keywords: "flowering succulent heat tolerant" , imageUrl: "https://images.pexels.com/photos/15135160/pexels-photo-15135160.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Serg Alesenko", photographerUrl: "https://www.pexels.com/@sergk1" },
  { category: "exterior-succulent", name: "Desert Rose (Adenium)", benefit: "Sculptural thick stems with decorative flowers.", care: "Full sun, minimal water.", keywords: "sculptural decorative pot" , imageUrl: "https://images.pexels.com/photos/236466/pexels-photo-236466.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "icon0 com", photographerUrl: "https://www.pexels.com/@icon0" },

  // ===== CLIMBERS =====
  { category: "exterior-climber", name: "Butterfly Pea (Clitoria ternatea)", benefit: "Hardy climber, suitable for terraces and entrances.", care: "Full sun to partial shade.", keywords: "climber terrace entrance blue flower" , imageUrl: "https://images.pexels.com/photos/8749622/pexels-photo-8749622.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Tamanna Rumee", photographerUrl: "https://www.pexels.com/@tamanna-rumee-52377920" },

  // ===== FRAGRANT / HERBAL (dual-purpose) =====
  { category: "exterior-shrub", name: "Lavender", benefit: "Fragrant, calming; ornamental and aromatic use.", care: "Full sun, well-drained soil.", keywords: "fragrant herb aromatic" , imageUrl: "https://images.pexels.com/photos/3259959/pexels-photo-3259959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Vito Vidović", photographerUrl: "https://www.pexels.com/@vito" },
  { category: "exterior-shrub", name: "Rosemary", benefit: "Culinary herb, also ornamental.", care: "Full sun, minimal water.", keywords: "culinary herb kitchen garden" , imageUrl: "https://images.pexels.com/photos/17677894/pexels-photo-17677894.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Red Nguyen", photographerUrl: "https://www.pexels.com/@rednguyen" },
  { category: "exterior-shrub", name: "Lemongrass", benefit: "Culinary/medicinal use; hardy grower.", care: "Full sun.", keywords: "culinary herb kitchen garden" , imageUrl: "https://images.pexels.com/photos/38004213/pexels-photo-38004213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "mingche lee", photographerUrl: "https://www.pexels.com/@mingche-lee-2072368" },

  // ===== LAWN GRASS =====
  { category: "lawn-grass", name: "Bermuda Grass (Doob hybrid)", benefit: "The most common Indian lawn grass; handles full sun and heavy traffic.", care: "Full sun; regular mowing.", keywords: "doob common sunny high traffic sports" , imageUrl: "https://images.pexels.com/photos/2300962/pexels-photo-2300962.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Christy Rice", photographerUrl: "https://www.pexels.com/@christy-rice-1208544" },
  { category: "lawn-grass", name: "Korean Grass (Zoysia)", benefit: "Premium, dense, soft ornamental lawn - the 'luxury' choice.", care: "Tolerates shade; slower growth, less mowing.", keywords: "premium luxury villa soft ornamental" , imageUrl: "https://images.pexels.com/photos/29254882/pexels-photo-29254882.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Alfredo Marco Pradil", photographerUrl: "https://www.pexels.com/@marcologous" },
  { category: "lawn-grass", name: "Mexican Grass", benefit: "Heat-tolerant, neat uniform appearance - popular for villas and hotels.", care: "Full sun.", keywords: "villa hotel decorative uniform" , imageUrl: "https://images.pexels.com/photos/8298153/pexels-photo-8298153.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "RDNE Stock project", photographerUrl: "https://www.pexels.com/@rdne" },
  { category: "lawn-grass", name: "Doob Grass (Cynodon dactylon)", benefit: "Traditional, sacred grass; drought-tolerant.", care: "Partial to full sun.", keywords: "traditional sacred religious drought" , imageUrl: "https://images.pexels.com/photos/17054112/pexels-photo-17054112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Marlon Alves", photographerUrl: "https://www.pexels.com/@marlon-alves-2016519" },
  { category: "lawn-grass", name: "Carpet Grass", benefit: "Shade-tolerant, budget-friendly for humid regions.", care: "Partial shade, moderate water.", keywords: "shade budget humid coastal" , imageUrl: "https://images.pexels.com/photos/5570942/pexels-photo-5570942.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Javi Moreno", photographerUrl: "https://www.pexels.com/@javi-moreno-16277" },
  { category: "lawn-grass", name: "Selection No. 1 Grass", benefit: "Premium, dark green, drought-resistant - used for high-end lawns.", care: "Less frequent mowing needed.", keywords: "premium dark green wedding high end" , imageUrl: "https://images.pexels.com/photos/11322011/pexels-photo-11322011.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "you-quan qiu", photographerUrl: "https://www.pexels.com/@you-quan-qiu-184984418" },
  { category: "lawn-grass", name: "St. Augustine Grass", benefit: "Broad leaves, good coverage for humid/coastal regions.", care: "Tolerates partial shade.", keywords: "coastal humid broad leaf shade" , imageUrl: "https://images.pexels.com/photos/38197226/pexels-photo-38197226.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Roy Serafin", photographerUrl: "https://www.pexels.com/@roythephotographer" },
  { category: "lawn-grass", name: "Nilgiri Grass", benefit: "Cool-season grass for hill stations and cooler regions.", care: "Cooler climate needed.", keywords: "hill station cool climate" , imageUrl: "https://images.pexels.com/photos/19073857/pexels-photo-19073857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Nur Salman", photographerUrl: "https://www.pexels.com/@nur-salman-483140031" },
];

export type GardenStyleEntry = {
  name: string;
  description: string;
  keywords: string;
  imageUrl?: string;
  photographerName?: string;
  photographerUrl?: string;
};

export const GARDEN_STYLE_ENTRIES: GardenStyleEntry[] = [
  { name: "Terrace Garden", description: "Container-based, often combining ornamental plants with a dedicated vegetable/herb section.", keywords: "terrace rooftop container vegetable" , imageUrl: "https://images.pexels.com/photos/15241687/pexels-photo-15241687.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Diego F. Parra", photographerUrl: "https://www.pexels.com/@diego-f-parra-33199" },
  { name: "Balcony Garden", description: "Railing planters, hanging pots, and space-efficient layouts for small areas.", keywords: "balcony small space railing" , imageUrl: "https://images.pexels.com/photos/13111771/pexels-photo-13111771.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Towfiqu barbhuiya", photographerUrl: "https://www.pexels.com/@towfiqu-barbhuiya-3440682" },
  { name: "Vertical / Wall Garden", description: "Tower structures, wall-mounted panels, or hanging cascades - makes the most of limited floor space.", keywords: "vertical wall green living wall tower" , imageUrl: "https://images.pexels.com/photos/7443025/pexels-photo-7443025.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "sukrit lamthong", photographerUrl: "https://www.pexels.com/@sukrit-lamthong-34482161" },
  { name: "Kitchen / Herb Garden", description: "Curry leaves, coriander, mint, fenugreek and similar - practical and decorative.", keywords: "kitchen herb curry leaves coriander" , imageUrl: "https://images.pexels.com/photos/1746410/pexels-photo-1746410.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Suzy Hazelwood", photographerUrl: "https://www.pexels.com/@suzyhazelwood" },
  { name: "Japanese-Style Garden", description: "Symbolic, miniature landscapes - pebbles as rivers, boulders as mountains, bonsai as trees.", keywords: "japanese zen bonsai pebble minimal" , imageUrl: "https://images.pexels.com/photos/8280940/pexels-photo-8280940.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Quang Nguyen Vinh", photographerUrl: "https://www.pexels.com/@quang-nguyen-vinh-222549" },
  { name: "English / Formal Garden", description: "Structured hedges, defined borders, symmetrical layout.", keywords: "formal hedge symmetrical structured" , imageUrl: "https://images.pexels.com/photos/126271/pexels-photo-126271.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Mike Bird", photographerUrl: "https://www.pexels.com/@mikebird" },
  { name: "Xeriscape / Succulent Garden", description: "Low-water, drought-tolerant plant focus - minimal maintenance.", keywords: "xeriscape drought low water succulent" , imageUrl: "https://images.pexels.com/photos/14562039/pexels-photo-14562039.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Magda Ehlers", photographerUrl: "https://www.pexels.com/@magda-ehlers-pexels" },
  { name: "Rock Garden", description: "Stone-based landscaping paired with hardy, low-maintenance plants.", keywords: "rock stone hardy low maintenance" , imageUrl: "https://images.pexels.com/photos/4973075/pexels-photo-4973075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Laura Link", photographerUrl: "https://www.pexels.com/@laura-link-2345390" },
  { name: "Rooftop Garden", description: "Full-sun tolerant species, often combining lawn areas with planters.", keywords: "rooftop terrace full sun" , imageUrl: "https://images.pexels.com/photos/15241687/pexels-photo-15241687.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", photographerName: "Diego F. Parra", photographerUrl: "https://www.pexels.com/@diego-f-parra-33199" },
];

export type PlanterMaterialEntry = {
  material: string;
  description: string;
};

export const PLANTER_MATERIALS: PlanterMaterialEntry[] = [
  { material: "Terracotta", description: "Breathable, traditional look - good for most plants." },
  { material: "Ceramic", description: "Decorative, wide range of styles and finishes." },
  { material: "Plastic", description: "Lightweight, budget-friendly, durable." },
  { material: "Metal", description: "Modern aesthetic; rust-proof options available." },
  { material: "Fiber / FRP", description: "Lightweight alternative that mimics ceramic or stone." },
  { material: "Jute / Coir", description: "Eco-friendly; commonly used for herbs and hanging planters." },
];
